# Generated by Django 5.1.6 on 2025-02-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tombamento', models.CharField(max_length=30)),
                ('tipo_de_disp', models.EmailField(max_length=254)),
                ('qnt_armaz', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('funcionando', models.CharField(max_length=6)),
                ('data_de_an', models.CharField(max_length=11)),
                ('locat_do_disp', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
